% Buses del MC con dos ejes y observadores codificados.
MCFF_Sensors=bus({'force','motorAngleT','motorAngleH','theta'});
MCFF_References=bus({'xRef','vRef','aRef','hoistVelocityRef','hoistAccelerationRef','swTransfer'});
MCFF_Commands=bus({'brakeOpen','E'},{'boolean','boolean'});
MCFF_DriveFeedback=bus({'deltaTorqueDelayed'});
MCFF_TrolleyState=bus({'x','omegaDrum','velocity','observerAngle'});
MCFF_HoistState=bus({'length','lengthRate','omegaDrum','observerAngle'});
MCFF_Parameters=bus({'Ts','gravity','r_td','i_t','M_EQt','b_EQt','Kx','Kp','Ki', ...
 'vmax','amax','Imax','r_hd','i_h','M_EQh','b_EQh','Khp','Khi','Khd', ...
 'length0','swayOnTime','swayFFRate','observerWn','observerZeta','obsA11','obsA12','obsA21','obsA22','obsB1','obsB2'});
MCFF_TrolleyDiagnostics=bus({'diag_torque_unsat','diag_vcmd','diag_vcmd_applied', ...
 'diag_vobs','diag_integral','diag_p','diag_i','diag_acmd','diag_acmd_applied','diag_ev', ...
 'aw_delta_a_limite','aw_delta_a_limite_memoria','aw_delta_a_torque','aw_delta_a_total', ...
 'aw_correccion_integrador','mc_integrator_input','antisway_correccion_aplicada', ...
 'sw_feedback_comun','sw_anticipacion_comun','sw_habilitacion_comun','diag_sw_unsat', ...
 'diag_sw_gain','angulo_referencia','diag_aff','diag_xref_input','diag_vref_input', ...
 'diag_aref_input','diag_xencoder','diag_omega_observer','diag_theta_medida', ...
 'diag_theta_eff','diag_brake_supervisor'});
MCFF_HoistDiagnostics=bus({'torque_izaje_consigna_controlador','mc_hoist_velocity_error', ...
 'mc_hoist_integral1','mc_hoist_integral2','mc_hoist_P','mc_hoist_D','mc_hoist_I','mc_hoist_FF'});
allNames=who('MCFF_*');
for k=1:numel(allNames),assignin('base',allNames{k},eval(allNames{k}));end
function b=bus(names,types)
if nargin<2,types=repmat({'double'},size(names));end
b=Simulink.Bus;
for j=1:numel(names)
 e=Simulink.BusElement;e.Name=names{j};e.DataType=types{j};e.Dimensions=1;
 if j==1,es=e;else,es(j)=e;end
end
b.Elements=es;
end
