% Mantiene las ganancias del MC probado. Discretiza solo observadores.
MC_FF=struct('Ts',T_s,'gravity',g,'r_td',r_td,'i_t',i_t,'M_EQt',M_EQt, ...
 'b_EQt',b_EQt,'Kx',K_x_cas,'Kp',K_pv_cas,'Ki',K_iv_cas, ...
 'vmax',v_tmax,'amax',dv_tmax,'Imax',dv_tmax/K_iv_cas, ...
 'r_hd',r_hd,'i_h',i_h,'M_EQh',M_EQh,'b_EQh',b_EQh, ...
 'Khp',K_hp,'Khi',K_hi,'Khd',K_hd,'length0',l_hi,'swayOnTime',T_SW_on, ...
 'swayFFRate',0.25,'observerWn',40.0,'observerZeta',1.0);
obsA=[-2*MC_FF.observerZeta*MC_FF.observerWn,1;-MC_FF.observerWn^2,0];
obsB=[2*MC_FF.observerZeta*MC_FF.observerWn;MC_FF.observerWn^2];
obsLeft=eye(2)-T_s/2*obsA;
obsAd=obsLeft\(eye(2)+T_s/2*obsA);obsBd=obsLeft\(T_s/2*obsB);
MC_FF.obsA11=obsAd(1,1);MC_FF.obsA12=obsAd(1,2);
MC_FF.obsA21=obsAd(2,1);MC_FF.obsA22=obsAd(2,2);
MC_FF.obsB1=obsBd(1);MC_FF.obsB2=obsBd(2);
assignin('base','MC_FF',MC_FF);
