function documentar_limite_ensayo(folder,out,q)
% Análisis de datos ya registrados: no escribe señales en el PLC.
meta=jsondecode(fileread(fullfile(folder,'metadatos.json')));
meta.pruebaValida=true;
meta.entregaCompleta=false;
meta.terminacion='Parada solicitada por el usuario al alcanzar tres minutos sin estabilizacion';
meta.limiteSolicitado_s=180;
meta.tiempoParadaEfectivo_s=q.lastT;
meta.observacionLimite='La instruccion llego cuando la simulacion ya habia superado 180 s. Se detuvo al recibirla y se conservaron todas las muestras, sin recortar los datos originales.';
meta.configuracionRelojes='Seguridad y supervisor por trama de 20 ms simulados; vigilancia OPC en tiempo real por latido independiente';
theta=out.logsout.get('angulo_fisico').Values;
omega=out.logsout.get('velocidad_angular_fisica').Values;
tm=theta.Time>=120 & theta.Time<=180;
wm=omega.Time>=120 & omega.Time<=180;
meta.balanceoUltimoMinuto=struct('intervalo_s',[120 180], ...
    'anguloRMS_rad',sqrt(mean(double(theta.Data(tm)).^2)), ...
    'anguloMax_rad',max(abs(double(theta.Data(tm)))), ...
    'omegaRMS_rad_s',sqrt(mean(double(omega.Data(wm)).^2)), ...
    'omegaMax_rad_s',max(abs(double(omega.Data(wm)))));
auto=q.telemetry(:,9)==4;
meta.inicioAuto_s=q.telemetry(find(auto,1),1);
meta.fallasDuranteManiobra=unique(q.telemetry(q.telemetry(:,1)>=q.events(1,2),14)).';
meta.emergenciasDuranteManiobra=any(q.telemetry(q.telemetry(:,1)>=q.events(1,2),12));
meta.watchdogDuranteManiobra=any(q.telemetry(q.telemetry(:,1)>=q.events(1,2),13));
meta.videoTipo='Captura en vivo de la visualizacion y HMI, 2 cuadros por segundo';
fid=fopen(fullfile(folder,'metadatos.json'),'w','n','UTF-8');fprintf(fid,'%s',jsonencode(meta,PrettyPrint=true));fclose(fid);
fig=figure('Visible','off','Position',[100 100 1200 800],'Color','w');
tiledlayout(2,2,'TileSpacing','compact','Padding','compact');
nexttile;plot(q.telemetry(:,1),q.telemetry(:,2),'LineWidth',1.2);yline(22.46,'--','Slot 22');ylabel('Posicion del carro [m]');title('Traslado al barco');grid on;xlim([0 q.lastT]);
nexttile;plot(q.telemetry(:,1),q.telemetry(:,3),'LineWidth',1.2);ylabel('Altura del spreader [m]');title('Carga suspendida, sin entrega');grid on;xlim([0 q.lastT]);
nexttile;plot(theta.Time,theta.Data,'LineWidth',1);yline(.005,'--');yline(-.005,'--');ylabel('Angulo [rad]');title('Balanceo: lineas +/-0,005 rad del descenso automatico');grid on;xlim([0 q.lastT]);
nexttile;plot(omega.Time,omega.Data,'LineWidth',1);yline(.012,'--');yline(-.012,'--');ylabel('Velocidad angular [rad/s]');title('Lineas +/-0,012 rad/s del descenso automatico');grid on;xlim([0 q.lastT]);
axs=findall(fig,'Type','axes');for k=1:numel(axs),xlabel(axs(k),'Tiempo de simulacion [s]');xline(axs(k),180,':','Limite solicitado');end
sgtitle('CODESYS manual SFC — sin antisway efectivo — prueba valida, entrega incompleta');
exportgraphics(fig,fullfile(folder,'resumen_sin_antisway.png'),'Resolution',160);close(fig);
fid=fopen(fullfile(folder,'README.md'),'w','n','UTF-8');
fprintf(fid,['# Prueba valida: CODESYS manual sin antisway efectivo\n\n' ...
'## Resultado\n\nLa prueba es valida como evaluacion del comportamiento sin antisway. No completo el medio ciclo ni se declara aprobada la entrega. El contenedor se tomo del slot 2, se elevo y se traslado al entorno del slot 22. Permanecio suspendido a la altura de cruce, sin estabilizarse para completar el descenso. No hubo apertura ni descarga.\n\n' ...
'El usuario indico detener al alcanzar 180 s. La instruccion llego despues de ese instante y la parada efectiva fue a %.2f s. Se conservaron todas las muestras y el video originales. No se presentan 180 s como tiempo efectivo de parada.\n\n' ...
'## Balanceo y fallas\n\nEn el intervalo [120,180] s: angulo RMS %.6f rad y maximo absoluto %.6f rad; velocidad angular RMS %.6f rad/s y maximo absoluto %.6f rad/s. Las lineas del resumen representan las condiciones angulares de comienzo del descenso automatico, no una certificacion de seguridad.\n\n' ...
'Fallas durante la maniobra: %s. Emergencia: %d. Watchdog: %d. La detencion final fue solicitada por el usuario, sin aumentar limites ni modificar ganancias.\n\n' ...
'## Verificacion y archivos\n\nLa verificacion nativa conserva los resultados de antisway efectiva cero y v_cmd igual a la referencia en el sumador. El perfil fisico del slot 2 disminuyo un contenedor; el slot 22 no cambio. Se registro carga fisica suspendida.\n\n' ...
'- datos_brutos.mat: salida Simulink completa, q del operador, perfil inicial, tiempos OPC y eventos de seguridad. Series con sus tiempos originales.\n' ...
'- datos_derivados.mat: magnitudes remuestreadas por tiempo y calculadas; no sustituyen los originales.\n' ...
'- catalogo_senales.csv y catalogo_senales_mc.csv: senales escalares, dinamica, torques y hojas de buses.\n' ...
'- eventos_modo.csv y eventos_maniobra.csv: solicitudes y transiciones efectivas, en segundos de simulacion.\n' ...
'- criterios.csv: comprobaciones individuales; entrega y fin de medio ciclo no aprobados. Esto no invalida el ensayo de control.\n' ...
'- metadatos.json y verificacion_nativa.mat: parametros, variante y mediciones de comprobacion.\n' ...
'- verificacion_watchdog_real.mat: vigilancia real del enlace comprobada antes del movimiento.\n' ...
'- resumen_sin_antisway.png, hmi_final_video.png y Video_prueba_conjunta: resumen y video en vivo de HMI y visualizacion.\n' ...
'- Copia del modelo realmente ejecutado y scripts para reproducir. La parada de esta corrida fue una orden del usuario; para repetir con corte automatico fijar previamente StopTime=180.\n\n' ...
'Video: %s.\n\nNo se ejecutaron corridas ST automaticas. La referencia con antisway requiere condiciones iniciales reinicializadas.\n'],q.lastT,meta.balanceoUltimoMinuto.anguloRMS_rad,meta.balanceoUltimoMinuto.anguloMax_rad,meta.balanceoUltimoMinuto.omegaRMS_rad_s,meta.balanceoUltimoMinuto.omegaMax_rad_s,mat2str(meta.fallasDuranteManiobra),meta.emergenciasDuranteManiobra,meta.watchdogDuranteManiobra,meta.video);
fclose(fid);
disp(meta.balanceoUltimoMinuto);
end
